version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-matchzone}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-matchzone}
      POSTGRES_DB: ${POSTGRES_DB:-matchzone}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports:
      - "${REDIS_PORT:-6379}:6379"
volumes:
  pgdata:
